server:
 port: 8091

springfox:
 title: 'FINT SSE Adapter Skeleton'
 version: '@version@'

base-url: https://play-with-fint-adapter.felleskomponent.no/provider
fint:
 adapter:
  organizations: pwfa.no
  sse-endpoint: ${base-url}/sse/%s
  status-endpoint: ${base-url}/status
  response-endpoint: ${base-url}/response

 oauth:
  enabled: true
  username: pwfatut
  password: pwfatut
  client-id: 6e1cf7b4-b107-42b3-9435-8fda70726c6a
  client-secret: 6y4FUuP9BfAXeVqguNKT0ofToIwN5RdB1PaUvx_nCMiQbH9NeGq3pp0jQB9zOQ0APOxEbodzJXp-8RVux6318A
  access-token-uri: https://namidp01.rogfk.no/nidp/oauth/nam/token